services:
  - type: web
    name: booking-app-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booking-app-db
          property: connectionString
      - key: NODE_ENV
        value: production

  - type: web
    name: booking-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://booking-app-backend.onrender.com/api

databases:
  - name: booking-app-db
    databaseName: booking_app
    user: booking_app
